In [25]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv(r"D:\\data analysis projects\\zip_data\\supply_chain\\supply_chain_data.csv")

In [7]:
data.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    str
 1   SKU                      100 non-null    str
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    str
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    str
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    str
 14  Location                 100 non-null    str
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    str
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    str
 22  Routes                   100 non-null    str
 23  Costs                    100 non-null    float64
dtypes: float64(6), int64(9), str(9)
memory usage: 18.9 KB

In [10]:
data.size

2400

In [16]:
data.dtypes

Product type                   str
SKU                            str
Price                      float64
Availability                 int64
Number of products sold      int64
Revenue generated          float64
Customer demographics          str
Stock levels                 int64
Lead times                   int64
Order quantities             int64
Shipping times               int64
Shipping carriers              str
Shipping costs             float64
Supplier name                  str
Location                       str
Lead time                    int64
Production volumes           int64
Manufacturing lead time      int64
Manufacturing costs        float64
Inspection results             str
Defect rates               float64
Transportation modes           str
Routes                         str
Costs                      float64
dtype: object

In [18]:
data.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [20]:
data.rename(columns={
    "Product type": "product_type",
    "SKU": "sku",
    "Price": "price",
    "Availability": "availability",
    "Number of products sold": "number_of_products_sold",
    "Revenue generated": "revenue",
    "Stock levels": "stock",
    "Lead times": "lead_time",
    "Order quantities": "order_quantities",
    "Shipping times": "shipping_time",
    "Shipping carriers": "shipping_carriers",
    "Shipping costs": "shipping_costs",
    "Supplier name": "supplier_name",
    "Location": "location",
    "Lead time": "lead_time",
    "Production volumes": "production_volumes",
    "Manufacturing lead time": "manufacturing_lead_time",
    "Manufacturing costs": "manufacturing_costs",
    "Inspection results": "inspection_results",
    "Defect rates": "defect_rates",
    "Transportation modes": "transportation_modes",
    "Routes": "routes",
    "Costs": "costs"
}, inplace=True)

In [22]:
data.columns

Index(['product_type', 'sku', 'price', 'availability',
       'number_of_products_sold', 'revenue', 'Customer demographics', 'stock',
       'lead_time', 'order_quantities', 'shipping_time', 'shipping_carriers',
       'shipping_costs', 'supplier_name', 'location', 'lead_time',
       'production_volumes', 'manufacturing_lead_time', 'manufacturing_costs',
       'inspection_results', 'defect_rates', 'transportation_modes', 'routes',
       'costs'],
      dtype='str')

In [23]:
data.describe()

,price,availability,number_of_products_sold,revenue,stock,lead_time,order_quantities,shipping_time,shipping_costs,lead_time,production_volumes,manufacturing_lead_time,manufacturing_costs,defect_rates,costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239831,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976921,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [28]:
numeric_columns = [
    "price",
    "availability",
    "number_of_products_sold",
    "revenue",
    "stock",
    "lead_time",
    "order_quantity",
    "shipping_time",
    "shipping_cost",
    "production_volume",
    "manufacturing_lead_time",
    "manufacturing_cost",
    "defect_rate",
    "costs"
]

In [29]:
data[numeric_columns].boxplot(figsize=(15, 8))
plt.xticks(rotation=45)
plt.show()

KeyError: "['order_quantity', 'shipping_cost', 'production_volume', 'manufacturing_cost', 'defect_rate'] not in index"